name: GKITS
main: AdvancedKits\Main
version: 5.2.3
api: [3.0.0]
author: QuiltedTuba2798
description: ADDS GKITS TO YOUR MINECRAFT SERVER
website: https://github.com/QuiltedTuba2798/gkits
softdepend: [PurePerms, PiggyCustomEnchants, FormAPI]
commands:
 gkit:
  description: Claim A Gkit
  usage: "/gkit [gkitname]"
  aliases: [godkit]
  permission: advancedkits.command
permissions:
 advancedkits.command:
  description: "Allows the user to run /kit command"
  default: true
 advancedkits.admin:
  description: "Allows to manage admin features"
  default: op
