---
# Users are able to get only one gkit per life
one-gkit-per-life: true

# Users are able to get a gkit if they log out even if they did not die (only works if one-gkit-per-life: true)
reset-on-logout: true

# Use built in permission system even if using PurePerms
force-builtin-permissions: false

# Sign text (capitals and color codes don't matter)
sign-text: "[gkits]"

# gkits you don't have the permission to get will be hidden from the kits list
hide-no-perm-gkits: false
...
